name: 'Discord Notify Webhook'
description: 'Send custom Discord Notify from GitHub Action'
branding:
  icon: bell
  color: green
inputs:
  webhook_url:
    description: 'Discord Webhook Url'
    required: true
  title:
    description: 'Title of embed'
    required: true
  description:
    description: 'Description of embed'
    required: true
  url:
    description: 'Url of embed'
    required: false
  color:
    description: 'Color code of the embed'
    required: false
  footer:
    description: 'Footer text'
    required: false
  footer_icon:
    description: 'Fotter Icon Url'
    required: false
  image:
    description: 'Image Url'
    required: false
  thumbnail:
    description: 'Thumbnail Url'
    required: false
  author:
    description: 'Name of author'
    required: false
  author_url:
    description: 'Url of author'
    required: false
  author_icon:
    description: 'Icon url of Author'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.cjs'