name: Discord Notify

on:
  push:
    branches:
      - main

jobs:
    Notify:
        runs-on: ubuntu-latest
        steps:
            - name: ch
              uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Install dependencies
              run: npm install
            - name: Discord Notify Webhook
              uses: EDUJOS/ds-webhook@v1.0.12
              with:
                webhook_url: https://discord.com/api/webhooks/1088959925553733703/ejVTaca1911utsx0ItAoUXsNrU0j2XiZ7MEICGrpBv6BXFSDgUZYg-aXEb9xKP7o7eX_
                title: Some Title
                description: Chupalo est es una prueba
